environment:
  matrix:
    - node_version: "6.2"
    - node_version: "6.1"
    - node_version: "6.0"

install:
  - ps: Install-Product node $env:node_version
  - npm install

test_script:
  - npm test

build: off